server:
  port: 9999
spring:
  application:
    name: tz-spider
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tz_sprider?characterEncoding=UTF-8
      username: root
      password: 123456